# minimal mistakes Jekyll reference
# https://github.com/mmistakes/minimal-mistakes/blob/master/docs/_config.yml

remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: "dark"

title: Panther
subtitle: "Powerful Autonomous eNTity High-End Robot"
name: &name "Raffaello Bonghi"
description: &description "Panther is an outdoor tracked robot. This robot can interact with all objects around it."
url: https://rpanther.github.io
repository: "rpanther/rpanther.github.io"
teaser: /assets/images/intro.jpg

search: true
search_full_content: true

# SEO Related
google_site_verification: "HzifDWPrlsejyq7zKJkACAiypLC66t7z5sfJqDkkOf8"

twitter:
  username: &twitter "raffaello86"

social:
  links: # An array of links to social media profiles
    - "https://twitter.com/raffaello86"
    - "https://instagram.com/robo.panther"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-92957365-3"
    anonymize_ip: false # default

author:
  name        : "Raffaello Bonghi"
  bio         : "Passion Robotics. Working in Robotics & AI. Ah Yes, in my spare time I work in robotics. Ph.D. in Robotics and automation engineer"
  avatar      : "https://rbonghi.github.io/assets/images/raffaello.jpg"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://rnext.it"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/raffaello86"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/raffaello-bonghi/"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/rbonghi"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/c/RaffaelloBonghi"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/robo.panther"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:raffaello@rnext.it"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/raffaello86"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/raffaello-bonghi/"
    - label: "Github"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/rbonghi"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/c/RaffaelloBonghi"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/robo.panther"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:raffaello@rnext.it"
    - label: "Terms"
      icon: "fas fa-fw fa-link"
      url: "/terms"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - README.md
  - LICENSE
  - Gemfile

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

collections:
  project:
    output: true
    permalink: /:collection/:path/
  control:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # project
  - scope:
      path: "_project"
      type: project
    values:
      layout: single
      author_profile: false
      share: true
      read_time: true
      sidebar:
        nav: "project"
  # control
  - scope:
      path: "_control"
      type: control
    values:
      layout: single
      author_profile: false
      share: true
      read_time: true
      sidebar:
        nav: "control"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
# timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

after_footer_scripts :
  - /assets/js/cookie-consent.js
  